---
title: "Exploratory Analysis"
author: "Richard G. Gardiner"
date: "2/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data and Packages

```{r}
library(tidyverse)
library(tidytext)
library(readxl)
```

```{r}
gavel <- read_excel("Gavel to Gavel dataset.xlsx")

str(gavel)
```

## Unnesting the tokens
```{r}
tidy_text <- gavel %>%
  unnest_tokens(word, Description) %>%
  anti_join(stop_words)
```

```{r}
tidy_text %>%
  count(word, sort = TRUE)
```

```{r}
tidy_text %>%
  group_by(curbing, Type) %>%
  count(word, sort = TRUE) %>%
  filter(n > 75) %>%
  filter(curbing == 1) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = Type)) +
  geom_col() +
  xlab(NULL) +
  facet_wrap(~ Type, scales = "free_y") +
  coord_flip()
```

```{r}
sentiments_bing_gavel <- tidy_text %>%
  inner_join(get_sentiments("bing"))

sentiments_bing_gavel %>%
  count(word, sentiment, sort = TRUE)
```


```{r}
sentiments_bing_gavel_2 <- sentiments_bing_gavel %>%
  count(sentiment, Year, Elected) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(net_sentiment = positive - negative)


ggplot(sentiments_bing_gavel_2, aes(x = Year, y = net_sentiment, fill = net_sentiment > 0)) +
  geom_col() +
  facet_wrap(~Elected)
```

```{r}
sentiments_afinn_gavel <- tidy_text %>%
  inner_join(get_sentiments("afinn"))

sentiments_afinn_gavel_2 <- sentiments_afinn_gavel %>%
  count(score, Year, Elected) %>%
  mutate(weighted_score = score * n) %>%
  spread(score, n, fill = 0) %>%
  select(Year, Elected, weighted_score) %>%
  group_by(Year, Elected) %>%
  summarize(total_score = sum(weighted_score))

ggplot(sentiments_afinn_gavel_2, 
       aes(x = Year, y = total_score, fill = total_score > 0)) +
  geom_col() +
  facet_wrap(~Elected)
```


## Figuring out the incorrectly classified

```{r}
word_bing <- sentiments_bing_gavel %>%
  count(word, sentiment, sort = TRUE)

write_csv(word_bing, "bing words.csv", na = "")
```


```{r}
word_afinn <- sentiments_afinn_gavel %>%
  count(word, score, sort = TRUE)

write_csv(word_afinn, "afinn words.csv", na = "")
```







